import { IStudent, Gender, StudentStatus, StudyForm, EntityType } from '../../dto';

export const MOCK_STUDENTS: IStudent[] = [
    {
        birthday: 926370000000,
        course: 3,
        faculty: {
            name: 'Radiophysics and Computer Technologies',
            displayName: 'RFaCT',
        },
        courseworkTeacher: { name: 'Isaac Newton' },
        entityType: EntityType.Students,
        fullName: 'Albert Einstein',
        gender: Gender.Male,
        group: { name: '1+5 AI' },
        hasPrivileges: false,
        lastSessionGPA: 8.5,
        location: 'Kurchatova 8, 143B',
        scholarship: 120,
        specialty: 'Applied Informatics',
        status: StudentStatus.Study,
        studyForm: StudyForm.Free,
        title: 'Albert Einstein',
        urlToAvatar:
            'https://www.biography.com/.image/t_share/MTE5NDg0MDU0OTU2OTAxOTAz/albert-einstein-9285408-1-402.jpg',
    },
    {
        birthday: 826370000000,
        course: 4,
        faculty: {
            name: 'Radiophysics and Computer Technologies',
            displayName: 'RFaCT',
        },
        courseworkTeacher: { name: 'Michael Faraday' },
        entityType: EntityType.Students,
        fullName: 'William Gilbert',
        gender: Gender.Male,
        group: { name: '5+7 CS' },
        hasPrivileges: true,
        lastSessionGPA: 6.4,
        location: 'No information',
        scholarship: 100,
        specialty: 'Computer Security',
        status: StudentStatus.AcademicVacation,
        studyForm: StudyForm.Paid,
        title: 'William Gilbert',
        urlToAvatar:
            'https://static1.squarespace.com/static/5793e055e6f2e155ae8d79d9/t/58c6013d1e5b6c36786b0bb9/1489371458218/',
    },
    {
        birthday: 626370000000,
        course: 2,
        faculty: {
            name: 'Radiophysics and Computer Technologies',
            displayName: 'RFaCT',
        },
        courseworkTeacher: { name: 'Max Planck' },
        entityType: EntityType.Students,
        fullName: 'Heinrich Hertz',
        gender: Gender.Male,
        group: { name: '5+7 CS' },
        hasPrivileges: true,
        lastSessionGPA: 5.1,
        location: 'Kurchatova 6, 516A',
        scholarship: 0,
        specialty: 'Computer Security',
        status: StudentStatus.Debt,
        studyForm: StudyForm.Paid,
        title: 'Heinrich Hertz',
        urlToAvatar: 'https://upload.wikimedia.org/wikipedia/commons/3/30/HEINRICH_HERTZ.JPG',
    },
    {
        birthday: 726370000000,
        course: 3,
        faculty: {
            name: 'Radiophysics and Computer Technologies',
            displayName: 'RFaCT',
        },
        courseworkTeacher: { name: 'Max Planck' },
        entityType: EntityType.Students,
        fullName: 'Emmy Noether',
        gender: Gender.Female,
        group: { name: '5+7 CS' },
        hasPrivileges: true,
        lastSessionGPA: 9.5,
        location: 'No information',
        scholarship: 120,
        specialty: 'Computer Security',
        status: StudentStatus.Study,
        studyForm: StudyForm.Free,
        title: 'Emmy Noether',
        urlToAvatar:
            'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/' +
            'Noether_retusche_nachcoloriert.jpg/220px-Noether_retusche_nachcoloriert.jpg',
    },
    {
        birthday: 726370000000,
        course: 3,
        faculty: {
            name: 'Radiophysics and Computer Technologies',
            displayName: 'RFaCT',
        },
        courseworkTeacher: { name: 'Max Planck' },
        entityType: EntityType.Students,
        fullName: 'Nikola Tesla',
        gender: Gender.Male,
        group: { name: '5+7 CS' },
        hasPrivileges: false,
        lastSessionGPA: 9.2,
        location: 'No information',
        scholarship: 120,
        specialty: 'Computer Security',
        status: StudentStatus.Study,
        studyForm: StudyForm.Free,
        title: 'Nikola Tesla',
        urlToAvatar: 'https://www.biographyonline.net/wp-content/uploads/2014/05/tesla2.jpg',
    },
    {
        birthday: 756370000000,
        course: 4,
        faculty: {
            name: 'Radiophysics and Computer Technologies',
            displayName: 'RFaCT',
        },
        courseworkTeacher: { name: 'Max Planck' },
        entityType: EntityType.Students,
        fullName: 'Galileo Galilei',
        gender: Gender.Male,
        group: { name: '5+7 CS' },
        hasPrivileges: false,
        lastSessionGPA: 8.0,
        location: 'No information',
        scholarship: 0,
        specialty: 'Computer Security',
        status: StudentStatus.Study,
        studyForm: StudyForm.Paid,
        title: 'Galileo Galilei',
        urlToAvatar: 'https://www.historyonthenet.com/wp-content/uploads/2014/07/galileogalilei.jpg',
    },
    {
        birthday: 756570000000,
        course: 1,
        faculty: {
            name: 'Radiophysics and Computer Technologies',
            displayName: 'RFaCT',
        },
        courseworkTeacher: { name: 'Max Planck' },
        entityType: EntityType.Students,
        fullName: 'Carl Friedrich Gauss',
        gender: Gender.Male,
        group: { name: '5+7 CS' },
        hasPrivileges: true,
        lastSessionGPA: 9.8,
        location: 'No information',
        scholarship: 120,
        specialty: 'Computer Security',
        status: StudentStatus.AcademicVacation,
        studyForm: StudyForm.Free,
        title: 'Carl Friedrich Gauss',
        urlToAvatar: 'https://cdn.britannica.com/s:300x300/27/190027-004-11966B78.jpg',
    },
    {
        birthday: 746570000000,
        course: 4,
        faculty: {
            name: 'Radiophysics and Computer Technologies',
            displayName: 'RFaCT',
        },
        courseworkTeacher: { name: 'Max Planck' },
        entityType: EntityType.Students,
        fullName: 'Isaac Newton',
        gender: Gender.Male,
        group: { name: '5+7 CS' },
        hasPrivileges: true,
        lastSessionGPA: 9.3,
        location: 'No information',
        scholarship: 120,
        specialty: 'Computer Security',
        status: StudentStatus.Study,
        studyForm: StudyForm.Free,
        title: 'Isaac Newton',
        urlToAvatar:
            'https://upload.wikimedia.org/wikipedia/commons/' +
            'thumb/3/39/GodfreyKneller-IsaacNewton-1689.jpg/220px-GodfreyKneller-IsaacNewton-1689.jpg',
    },
];
