import { IStudent, Gender, StudentStatus, StudyForm } from '../../dto';

export const MOCK_STUDENTS: IStudent[] = [
    {
        birthday: 926370000000,
        course: 3,
        faculty: {
            name: 'Radiophysics and Computer Technologies',
            displayName: 'RFaCT',
        },
        courseworkTeacher: { name: 'Isaac Newton' },
        fullName: 'Albert Einstein',
        gender: Gender.Male,
        group: { name: '1+5 AI' },
        hasPrivileges: false,
        lastSessionGPA: 8.5,
        location: 'Kurchatova 8, 143B',
        scholarship: 120,
        specialty: 'Applied Informatics',
        status: StudentStatus.Study,
        studyForm: StudyForm.Free,
        urlToAvatar:
            'https://www.biography.com/.image/t_share/MTE5NDg0MDU0OTU2OTAxOTAz/albert-einstein-9285408-1-402.jpg',
    },
    {
        birthday: 826370000000,
        course: 4,
        faculty: {
            name: 'Radiophysics and Computer Technologies',
            displayName: 'RFaCT',
        },
        courseworkTeacher: { name: 'Michael Faraday' },
        fullName: 'William Gilbert',
        gender: Gender.Male,
        group: { name: '5+7 CS' },
        hasPrivileges: true,
        lastSessionGPA: 6.4,
        location: 'No information',
        scholarship: 100,
        specialty: 'Computer Security',
        status: StudentStatus.AcademicVacation,
        studyForm: StudyForm.Paid,
        urlToAvatar:
            'https://static1.squarespace.com/static/5793e055e6f2e155ae8d79d9/t/58c6013d1e5b6c36786b0bb9/1489371458218/',
    },
    {
        birthday: 626370000000,
        course: 2,
        faculty: {
            name: 'Radiophysics and Computer Technologies',
            displayName: 'RFaCT',
        },
        courseworkTeacher: { name: 'Max Planck' },
        fullName: 'Heinrich Hertz',
        gender: Gender.Male,
        group: { name: '5+7 CS' },
        hasPrivileges: true,
        lastSessionGPA: 5.1,
        location: 'Kurchatova 6, 516A',
        scholarship: 0,
        specialty: 'Computer Security',
        status: StudentStatus.Debt,
        studyForm: StudyForm.Paid,
        urlToAvatar: 'https://www.famousscientists.org/80/80-heinrich-hertz.jpg',
    },
    {
        birthday: 726370000000,
        course: 3,
        faculty: {
            name: 'Radiophysics and Computer Technologies',
            displayName: 'RFaCT',
        },
        courseworkTeacher: { name: 'Max Planck' },
        fullName: 'Emmy Noether',
        gender: Gender.Female,
        group: { name: '5+7 CS' },
        hasPrivileges: true,
        lastSessionGPA: 9.5,
        location: 'No information',
        scholarship: 120,
        specialty: 'Computer Security',
        status: StudentStatus.Study,
        studyForm: StudyForm.Free,
        urlToAvatar: 'https://www.famousscientists.org/80/80-emmy-noether.jpg',
    },
];
